// Uploads the variants generated by scripts/process.ts to Cloudflare R2.
// Runs locally only; credentials come from .env (see .env.example).

import { join } from "node:path";
import { FORMATS, type Photo } from "../src/data/types";

const OUT_DIR = ".cache/out";
const MANIFEST = "src/data/photos.json";
const CONTENT_TYPES = { avif: "image/avif", webp: "image/webp", jpg: "image/jpeg" } as const;

function requireEnv(name: string) {
  const value = Bun.env[name];
  if (!value) {
    console.error(`Missing ${name}. Copy .env.example to .env and fill it in.`);
    process.exit(1);
  }
  return value;
}

const client = new Bun.S3Client({
  endpoint: `https://${requireEnv("R2_ACCOUNT_ID")}.r2.cloudflarestorage.com`,
  accessKeyId: requireEnv("R2_ACCESS_KEY_ID"),
  secretAccessKey: requireEnv("R2_SECRET_ACCESS_KEY"),
  bucket: requireEnv("R2_BUCKET"),
  region: "auto",
});

const photos: Photo[] = await Bun.file(MANIFEST).json();
let uploaded = 0;
let skipped = 0;

for (const photo of photos) {
  for (const w of photo.widths) {
    for (const f of FORMATS) {
      // Keys contain a content hash, so an existing key never needs replacing.
      const key = `${photo.id}/${w}.${f}`;
      if (await client.exists(key)) {
        skipped++;
        continue;
      }
      const local = Bun.file(join(OUT_DIR, key));
      if (!(await local.exists())) {
        console.error(`Missing ${local.name} — run \`bun run process\` first.`);
        process.exit(1);
      }
      await client.write(key, local, { type: CONTENT_TYPES[f] });
      uploaded++;
      console.log(`  up    ${key}`);
    }
  }
}

console.log(`Uploaded ${uploaded}, already present ${skipped}.`);
